name: Build & Release (Self-contained / Single-file)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.editorconfig'

permissions:
  contents: write
  packages: read

env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: Release
  PROJECT_PATH: 'TelegramMonitor/TelegramMonitor.csproj'

concurrency:
  group: auto-release-${{ github.ref }}
  cancel-in-progress: true

jobs:



  prepare:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.ver.outputs.VERSION }}
    steps:
      - id: ver
        shell: bash
        run: |
          VERSION=$(TZ='Asia/Shanghai' date +'%Y.%m.%d.%H%M')
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "$VERSION" > version.txt
      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
          retention-days: 1




  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: linux-64,      rid: linux-x64,  artifact: TelegramMonitor-linux-64.tar.gz,  pack: "tar -czf" }
          - { name: linux-arm64,   rid: linux-arm64,artifact: TelegramMonitor-linux-arm64.tar.gz,pack: "tar -czf" }
          - { name: osx-64,        rid: osx-x64,    artifact: TelegramMonitor-osx-64.zip,       pack: "zip -r -q" }
          - { name: osx-arm64,     rid: osx-arm64,  artifact: TelegramMonitor-osx-arm64.zip,    pack: "zip -r -q" }
          - { name: windows-32,    rid: win-x86,    artifact: TelegramMonitor-windows-32.zip,   pack: "zip -r -q" }
          - { name: windows-64,    rid: win-x64,    artifact: TelegramMonitor-windows-64.zip,   pack: "zip -r -q" }
          - { name: windows-arm64, rid: win-arm64,  artifact: TelegramMonitor-windows-arm64.zip,pack: "zip -r -q" }
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publish (self-contained single-file)
        shell: bash
        run: |
          set -euo pipefail
          dotnet publish "${{ env.PROJECT_PATH }}" \
            --configuration "$CONFIGURATION" \
            -r "${{ matrix.rid }}" \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o "out/${{ matrix.rid }}"
          find "out/${{ matrix.rid }}" -type f \( -name '*.pdb' -o -name '*.xml' \) -delete
          cd "out/${{ matrix.rid }}"
          ${{ matrix.pack }} "../${{ matrix.artifact }}" .
          cd ../..
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: out/${{ matrix.artifact }}
          retention-days: 3




  release:
    if: github.repository == 'Riniba/TelegramMonitor'
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - id: meta
        shell: bash
        run: |
          echo "DATETIME=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日 %H:%M:%S')" >> "$GITHUB_OUTPUT"
          echo "COMMIT_MSG=$(git log -1 --pretty=format:'%s')" >> "$GITHUB_OUTPUT"
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.prepare.outputs.VERSION }}
          name: "Release ${{ needs.prepare.outputs.VERSION }}"
          body: |
            

            **发布时间：** ${{ steps.meta.outputs.DATETIME }}  
            **发布者：** ${{ github.actor }}

            **更新内容**  
            ${{ steps.meta.outputs.COMMIT_MSG }}

            
            Windows (x64 / x86 / ARM64)  
            Linux (x64 / ARM64)  
            macOS (Intel / Apple Silicon)  

            
            Windows 用户请下载对应系统架构的 zip 文件  
            • 64 位系统：`TelegramMonitor-windows-64.zip`  
            • 32 位系统：`TelegramMonitor-windows-32.zip`  
            • ARM64 系统：`TelegramMonitor-windows-arm64.zip`  

            Linux 用户请下载对应架构的 tar.gz 文件  
            • x64 架构：`TelegramMonitor-linux-64.tar.gz`  
            • ARM64 架构：`TelegramMonitor-linux-arm64.tar.gz`  

            macOS 用户请下载对应架构的 zip 文件  
            • Intel 芯片：`TelegramMonitor-osx-64.zip`  
            • Apple Silicon：`TelegramMonitor-osx-arm64.zip`
          files: |
            artifacts/**/*.zip
            artifacts/**/*.tar.gz
          draft: false
          prerelease: false
